print("         ------- Calorie Tracker --------")
print("\n")
print("-" * 40)
print("------- Food Calories Reference Table -------")
print(f"{'Food':<20}{'Calories'}")
print(f"{'Eggs':<20}{'155'}")
print(f"{'Oatmeal':<20}{'150'}")
print(f"{'Chicken Breast':<20}{'165'}")
print(f"{'Salad':<20}{'100'}")
print(f"{'Rice (1 cup)':<20}{'205'}")
print(f"{'Banana':<20}{'89'}")
print(f"{'Apple':<20}{'95'}")
print(f"{'Bread (1 slice)':<20}{'80'}")

print("\n")
print(f"{'Meal Type':>23}")
meal_type = ["Braekfast", "Lunch", "Dinner"]
print(meal_type)
print("\n")
print("Breakfast")
breakfast = input("Food: ")
calories1 = float(input("calories: "))

print("\n")
print("Lunch")
lunch = input("Food: ")
calories2 = float(input("calories: "))

print("\n")
print("Dinner")
dinner = input("Food: ")
calories3 = float(input("calories: "))


total = (calories1 + calories2 + calories3)
total_calories = total

print("\n")
print("Calories Table")
print("-"* 40)
print(f"{'Meal':<12}{'Food':<20}{'Calories'}")
print("-"* 40)
print(f"{'Breakfast':<12}{breakfast:<20}{calories1}")
print(f"{'Lunch':<12}{lunch:<20}{calories2}")
print(f"{'Dinner':<12}{dinner:<20}{calories3}")
print("-"* 40)
print(f"{'total calories':<32}{total}")
print("\n")


print(f"{'You consumed {total} calorie.'}")
print("Here's a suggested table for workouts/exercises to burn your calories:")
print("\n")
print("-----Workout Calories Burn Table-----")
print(f"{'Exercise':<20}{'Calories Burned/30 min'}")
print("-" * 40)
print(f"{'Running':<20}{'300'}")
print(f"{'Walking':<20}{'150'}")
print(f"{'Cycling':<20}{'250'}")
print(f"{'Swimming':<20}{'275'}")
print(f"{'Yoga':<20}{'120'}")
print(f"{'Jump Rope':<20}{'400'}")

print("Thank You!")
